version: 2

sources:
  - name: erp
    description: Fonte do ponto de vendas da northwind
    schema: erp_northwind
    tables:

      - name: employees
        description: Tabela com informações de funcionários.
        columns:
          - name: employee_id
            description: Chave primária da tabela funcionários.
            tests:
              - unique
              - not_null

      - name: products
        description: Tabela com informações de produtos.
        columns:
          - name: product_id
            description: Chave primária da tabela produtos.
            tests:
              - unique
              - not_null
      
      - name: orders
        description: Tabela com informações de vendas.
        columns:
          - name: order_id
            description: Chave primária da tabela orders.
            tests:
              - unique
              - not_null

      - name: order_details
        description: Tabela com informações de detalhes da venda.

      - name: customers
        description: Tabela com informações de detalhes de clientes.
      
      - name: suppliers
        description: Tabela com informações de detalhes de fornecedores.
      
      - name: categories
        description: Tabela com informações de detalhes de categorias.
