version: 2

sources:
  - name: erp
    description: Fonte do ponto de vendas da northwind
    schema: erp_northwind
    tables:

      - name: employees
        description: Tabela com informações de funcionários.
        columns:
          - name: employee_id
            description: Chave primária da tabela funcionários.
            tests:
              - unique
              - not_null

      - name: products
        description: Tabela com informações de produtos.
        columns:
          - name: product_id
            description: Chave primária da tabela produtos.
            tests:
              - unique
              - not_null
